gui:
  theme:
    activeBorderColor:
      - "#c4a7e7"  # iris
      - bold
    inactiveBorderColor:
      - "#6e6a86"  # muted
    optionsTextColor:
      - "#c4a7e7"  # iris
    selectedLineBgColor:
      - "#26233a"  # surface
    cherryPickedCommitBgColor:
      - "#403d52"  # overlay
    cherryPickedCommitFgColor:
      - "#c4a7e7"  # iris
    unstagedChangesColor:
      - "#eb6f92"  # love
    defaultFgColor:
      - "#e0def4"  # text
    searchingActiveBorderColor:
      - "#f6c177"  # gold

  authorColors:
    "*": "#ebbcba"  # rose

git:
  paging:
    colorArg: always
    useConfig: true
